name: TTLock Automation
on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-ttlock-automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download bookings.csv from Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/15dlVRicq93vepohGlRvWccRN9zJc6y5dMJQ_UWbdFC0/export?format=csv&gid=1119920792" -o bookings.csv
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Fetch and process bookings
        run: |
          echo "Processing bookings from bookings.csv"
          if [ -f "bookings.csv" ]; then
            echo "bookings.csv found"
            cat bookings.csv
          else
            echo "Warning: bookings.csv not found in repository root"
          fi
      
      - name: Run TTLock automation script
        run: |
          echo "Running multi_property_all_in_one.py"
          if [ -f "multi_property_all_in_one.py" ]; then
            python multi_property_all_in_one.py
          else
            echo "Error: multi_property_all_in_one.py not found in repository root"
            exit 1
          fi
      
      - name: Show results
        if: always()
        run: |
          echo "Automation workflow completed"
          echo "Check the logs above for detailed results"
